"use client";

import { useQuery } from "@tanstack/react-query";
import { useEffect, useState } from "react";
import { fetchInvoiceDetail } from "@/lib/api";

interface FundingProgressTrackerProps { invoiceId: string; target: number; raised?: number | null; investorCount?: number; deadline?: string | null; }
function formatAmount(a: number) { return a.toLocaleString(undefined, { minimumFractionDigits: 0, maximumFractionDigits: 2 }); }
function Countdown({ deadline }: { deadline: string }) { const [r, setR] = useState(""); useEffect(() => { function t() { const d = new Date(deadline).getTime() - Date.now(); if (d <= 0) { setR("Expired"); return; } const dy = Math.floor(d / 86_400_000); const h = Math.floor((d % 86_400_000) / 3_600_000); const m = Math.floor((d % 3_600_000) / 60_000); setR(dy > 0 ? `${dy}d ${h}h` : h > 0 ? `${h}h ${m}m` : `${m}m left`); } t(); const i = setInterval(t, 60_000); return () => clearInterval(i); }, [deadline]); return <span className={`text-sm ${r === "Expired" ? "text-red-500" : "text-muted-foreground"}`}>{r || "—"}</span>; }
export function FundingProgressTracker({ invoiceId, target, raised: rp, investorCount: cp, deadline }: FundingProgressTrackerProps) { const { data } = useQuery({ queryKey: ["invoice-funding", invoiceId], queryFn: () => fetchInvoiceDetail(invoiceId), refetchInterval: 30_000, staleTime: 15_000 }); const raised = data?.raised ?? rp ?? 0; const ic = data?.investorCount ?? cp ?? 0; const ff = target > 0 && raised >= target; const pct = target > 0 ? Math.min((raised / target) * 100, 100) : 0; return (<div className="space-y-3" data-testid="funding-progress-tracker"><div><div className="mb-2 flex justify-between text-sm"><span>Funding Progress</span><span className="font-semibold">{pct.toFixed(1)}%</span></div><div className="h-3 w-full overflow-hidden rounded-full bg-secondary"><div role="progressbar" aria-valuenow={Math.round(pct)} className={`h-full rounded-full transition-all duration-1000 ${ff ? "bg-green-500" : "bg-primary"}`} style={{ width: `${pct}%` }} /></div></div><div className="flex flex-wrap items-center justify-between gap-2"><p className="text-sm text-muted-foreground">{formatAmount(raised)} XLM of {formatAmount(target)} XLM</p><div className="flex items-center gap-3">{ff && <span className="rounded-full bg-green-100 px-2.5 py-0.5 text-xs font-semibold text-green-800">Fully Funded</span>}<span className="text-sm text-muted-foreground" data-testid="investor-count">{ic} {ic === 1 ? "investor" : "investors"}</span>{deadline && <Countdown deadline={deadline} />}</div></div>{deadline && new Date(deadline).getTime() < Date.now() && !ff && <div className="rounded-md bg-red-50 p-2 text-center text-sm font-medium text-red-700">Funding deadline has expired</div>}</div>); }
