"use client";
import { useQuery } from "@tanstack/react-query";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { useState } from "react";

interface M { totalInvoices: number; totalFunded: number; activeInvestors: number; settlementRate: number; statusBreakdown: Record<string, number>; recentActivity: { id: string; description: string; timestamp: string }[]; }
function SC({ title, value }: { title: string; value: string | number }) { return <Card><CardHeader className="pb-2"><CardTitle className="text-sm text-muted-foreground">{title}</CardTitle></CardHeader><CardContent><p className="text-2xl font-bold">{value}</p></CardContent></Card>; }
function chart(b: Record<string, number>) { const t = Object.values(b).reduce((a, c) => a + c, 0) || 1; const c: Record<string, string> = { submitted: "bg-blue-500", active: "bg-amber-500", funded: "bg-green-500", settled: "bg-emerald-700", rejected: "bg-red-500" }; return <Card><CardHeader><CardTitle className="text-sm">Status Breakdown</CardTitle></CardHeader><CardContent className="space-y-3"><div className="flex h-4 w-full rounded-full overflow-hidden">{Object.entries(b).map(([s, n]) => <div key={s} className={`${c[s] ?? "bg-gray-300"} h-full`} style={{ width: `${(n / t) * 100}%` }} title={`${s}: ${n}`} />)}</div><div className="flex flex-wrap gap-3 text-xs text-muted-foreground">{Object.entries(b).map(([s, n]) => <div key={s} className="flex items-center gap-1"><div className={`h-2.5 w-2.5 rounded-full ${c[s] ?? "bg-gray-300"}`} /><span className="capitalize">{s}</span> <span className="font-medium text-foreground">{n}</span></div>)}</div></CardContent></Card>; }

export function AdminMetricsDashboard() {
  const [r, setR] = useState<"7d" | "30d" | "90d" | "all">("30d");
  const { data, isLoading } = useQuery<M>({ queryKey: ["admin-metrics", r], queryFn: async () => { const res = await fetch(`/api/admin/metrics?range=${r}`); if (!res.ok) throw new Error("Failed"); return res.json(); } });
  if (isLoading) return <div className="grid grid-cols-2 md:grid-cols-4 gap-4">{[1, 2, 3, 4].map((i) => <Card key={i} className="h-28 animate-pulse bg-muted" />)}</div>;
  const m = data ?? { totalInvoices: 0, totalFunded: 0, activeInvestors: 0, settlementRate: 0, statusBreakdown: {}, recentActivity: [] };
  const csv = () => { const rows = [["Metric", "Value"], ["Total Invoices", m.totalInvoices], ["Total Funded", m.totalFunded], ["Active Investors", m.activeInvestors], ["Settlement Rate", `${m.settlementRate}%`], [""], ["Status", "Count"], ...Object.entries(m.statusBreakdown)]; const b = new Blob([rows.map((r) => r.join(",")).join("\n")], { type: "text/csv" }); const a = document.createElement("a"); a.href = URL.createObjectURL(b); a.download = `metrics-${r}.csv`; a.click(); };
  return (<div className="space-y-6"><div className="flex items-center justify-between"><h2 className="text-lg font-semibold">Platform Metrics</h2><div className="flex items-center gap-2"><div className="flex rounded-md border">{(["7d", "30d", "90d", "all"] as const).map((v) => <button key={v} onClick={() => setR(v)} className={`px-3 py-1 text-xs font-medium ${r === v ? "bg-primary text-primary-foreground" : "text-muted-foreground hover:bg-muted"}`}>{v === "all" ? "All" : v}</button>)}</div><Button variant="outline" size="sm" onClick={csv}>Export CSV</Button></div></div><div className="grid grid-cols-2 md:grid-cols-4 gap-4"><SC title="Total Invoices" value={m.totalInvoices} /><SC title="Total Funded" value={`${m.totalFunded.toLocaleString()} XLM`} /><SC title="Active Investors" value={m.activeInvestors} /><SC title="Settlement Rate" value={`${m.settlementRate}%`} /></div>{chart(m.statusBreakdown)}<Card><CardHeader><CardTitle className="text-sm">Recent Activity</CardTitle></CardHeader><CardContent>{m.recentActivity.length === 0 ? <p className="text-sm text-muted-foreground">No activity</p> : <ul className="space-y-3">{m.recentActivity.map((e) => <li key={e.id} className="flex gap-3 text-sm"><span className="mt-1 h-2 w-2 rounded-full bg-primary shrink-0" /><div><p>{e.description}</p><p className="text-xs text-muted-foreground">{new Date(e.timestamp).toLocaleString()}</p></div></li>)}</ul>}</CardContent></Card></div>);
}
